version: '3'

services:
  es:
    image: elasticsearch:6.8.13
    restart: always
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      discovery.type: single-node
    volumes:
      - es6data:/usr/share/elasticsearch/data
      # - full_path_to/custom_elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml

volumes:
  es6data:
