version: '3'

services:
  minio:
    image: minio/minio
:RELEASE.2021-05-22T02-34-39Z
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - minio:/data
    ports:
      - 9000:9000

volumes:
  minio: