version: '3'

services:
  mongo:
    image: mongo:3.6.19
    restart: always
    volumes:
#      - /Users/wolf/foo:/data/db
      - mg3data:/data/db
      # - ~/data/mongo/configdb:/data/configdb
    ports:
      - 27017:27017
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: root
#      MONGO_INITDB_ROOT_PASSWORD: root

volumes:
  mg3data:
