version: '3'

services:
  mysql:
    image: mysql:5.6
    command:
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mydata:/var/lib/postgresql/data

volumes:
  mydata: