version: '3'

services:
  pg:
    image: postgres:13.2
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: root
    volumes:
      - pg13:/var/lib/postgresql/data

volumes:
  pg13: